### ISSUE TITLE
Locking doesn't work

### ISSUE THREAD

**Issue by AndiLavera** [andrewc910/manjaro-eos#8]
Cannot `lock` a session however you can `suspend`. Journal shows the following error:

```sh
Sep 21 15:57:20 wingpanel[9557]: Indicator.vala:201: Unable to lock: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: This method is not implemented
```

I know David from the Elementary team is working on getting rid of light-locker and building a lock screen into Gala. This may be related to that. We may need to wait until Elementary 6.0 to get this one fixed.

**Comment by andrewc910** [comment]
Fixed.

**Comment by AndiLavera** [comment]
I was wrong. Fixing the session errors fixed this.
